server:
  port: 8081

spring:
 application:
   name: discovery-server
security:
  user:
    name: usuario
    password: otrapassword

eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka
